Source/OLLLibrarySystem/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OLLLibrarySystem.Domain.Abstract;
using OLLLibrarySystem.Domain.Entities;
using OLLLibrarySystem.WebUI.Models;

namespace OLLLibrarySystem.WebUI.Controllers
{
    public class BookController : Controller
    {
        private IEntitiesRepository repository;
        public int PageSize = 4;

        public BookController(IEntitiesRepository bookRepository)
        {
            this.repository = bookRepository;
        }

        public ViewResult List(string genre, int page = 1)
        {
            var books = repository.Book
                            .Where(p => genre == null || p.Genre == genre)
                            .OrderBy(p => p.BookID)
                            .Skip((page - 1) * PageSize)
                            .Take(PageSize);

            var bookViews = books.Join(repository.CheckedOutIn
                                      , b => b.CheckedOutInID
                                      , c => c.CheckedOutInID
                                      , (b, c) => new BookStatusView
                                      {
                                          book = b,
                                          status = c.Status
                                      });

            var bookLocations = books.Join(repository.Location
                          , b => b.LocationID
                          , l => l.LocationID
                          , (b, l) => new BookStatusView
                          {
                              book = b,
                              location = l.Description
                          });

            BookListViewModel model = new BookListViewModel
            {
                Book = bookViews,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = genre == null ?
                        repository.Book.Count() :
                        repository.Book.Where(e => e.Genre == genre).Count()
                },
                CurrentGenre = genre

                
            };
            return View(model);
        }

        public FileContentResult GetImage(int bookId)
        {
            Book b = repository.Book
                .FirstOrDefault(p => p.BookID == bookId);
            if (b != null)
            {
                return File(b.PhotoData, b.PhotoMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

Source/OLLLibrarySystem/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OLLLibrarySystem.Domain.Abstract;
using OLLLibrarySystem.Domain.Entities;
using OLLLibrarySystem.WebUI.Models;

namespace OLLLibrarySystem.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IEntitiesRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IEntitiesRepository repo, IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                ReturnUrl = returnUrl,
                Cart = cart
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int bookId,
                string returnUrl)
        {
            Book book = repository.Book
                .FirstOrDefault(p => p.BookID == bookId);

            if (book != null)
            {
                cart.AddItem(book, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int bookId,
                string returnUrl)
        {
            Book book = repository.Book
                .FirstOrDefault(p => p.BookID == bookId);

            if (book != null)
            {                
                cart.ReduceItem(book, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
    }
}

Source/OLLLibrarySystem/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OLLLibrarySystem.Domain.Abstract;

namespace OLLLibrarySystem.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IEntitiesRepository repository;

        public NavController(IEntitiesRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string genre = null)
        {

            ViewBag.SelectedGenre = genre;

            IEnumerable<string> genres = repository.Book
                                    .Select(x => x.Genre)
                                    .Distinct()
                                    .OrderBy(x => x);

            return PartialView(genres);
        }
    }
}

Source/OLLLibrarySystem/Views/Shared/BookSummary.cshtml
@using OLLLibrarySystem.WebUI.Models
@model BookStatusView

<div class="well">

    @if (Model.book.PhotoData != null)
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" width="75" height="75"
                 src="@Url.Action("GetImage", "Book",
                new { Model.book.BookID })" />
        </div>
    }

        <h3>
            <strong><I>@Model.book.BookTitle</I></strong>
            <span class="lead">by @Model.book.Author</span>
            <span class="label label-warning pull-right">@Model.status</span>

        </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {

        <div class="pull-right">
            @Html.Hidden("bookId", Model.book.BookID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart" />
        </div>
    }


    <span class="lead"> @Model.book.Description</span>
    <span class="lead">@Model.location</span>

</div>

Source/OLLLibrarySystem/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

Source/OLLLibrarySystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="~/Admin/Index">Lourdes Academy Library System</a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>