Source/OLLLibrarySystem/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OLLLibrarySystem.Domain.Abstract;
using OLLLibrarySystem.Domain.Entities;

namespace OLLLibrarySystem.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IEntitiesRepository repository;

        public AdminController(IEntitiesRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.Book);
        }

        public ViewResult Edit(int bookId)
        {
            Book book = repository.Book
                .FirstOrDefault(p => p.BookID == bookId);
            return View(book);
        }

        [HttpPost]
        public ActionResult Edit(Book book, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    book.PhotoMimeType = image.ContentType;
                    book.PhotoData = new byte[image.ContentLength];
                    image.InputStream.Read(book.PhotoData, 0, image.ContentLength);
                }

                repository.SaveBook(book);
                TempData["message"] = string.Format("{0} has been saved", book.BookTitle);
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(book);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new Book());
        }

        [HttpPost]
        public ActionResult Delete(int bookId)
        {
            Book deletedBook = repository.DeleteBook(bookId);
            if (deletedBook != null)
            {
                TempData["message"] = string.Format("{0} was deleted",
                    deletedBook.BookTitle);
            }
            return RedirectToAction("Index");
        }
    }
}

Source/OLLLibrarySystem/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OLLLibrarySystem.Domain.Abstract;
using OLLLibrarySystem.Domain.Entities;
using OLLLibrarySystem.WebUI.Models;

namespace OLLLibrarySystem.WebUI.Controllers
{
    public class BookController : Controller
    {
        private IEntitiesRepository repository;
        public int PageSize = 4;

        public BookController(IEntitiesRepository bookRepository)
        {
            this.repository = bookRepository;
        }

        public ViewResult List(string genre, int page = 1)
        {
            var books = repository.Book
                            .Where(p => genre == null || p.Genre == genre)
                            .OrderBy(p => p.BookID)
                            .Skip((page - 1) * PageSize)
                            .Take(PageSize);

            var bookViews = books.Join(repository.CheckedOutIn
                                      , b => b.CheckedOutInID
                                      , c => c.CheckedOutInID
                                      , (b, c) => new BookStatusView
                                      {
                                          book = b,
                                          status = c.Status
                                      });

            var bookLocations = books.Join(repository.Location
                          , b => b.LocationID
                          , l => l.LocationID
                          , (b, l) => new BookStatusView
                          {
                              book = b,
                              location = l.Description
                          });

            BookListViewModel model = new BookListViewModel
            {
                Book = bookViews,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = genre == null ?
                        repository.Book.Count() :
                        repository.Book.Where(e => e.Genre == genre).Count()
                },
                CurrentGenre = genre

                
            };
            return View(model);
        }

        public FileContentResult GetImage(int bookId)
        {
            Book b = repository.Book
                .FirstOrDefault(p => p.BookID == bookId);
            if (b != null)
            {
                return File(b.PhotoData, b.PhotoMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

Source/OLLLibrarySystem/Views/Admin/Edit.cshtml
@model OLLLibrarySystem.Domain.Entities.Book

@{
    ViewBag.Title = "Admin: Edit " + @Model.BookTitle;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Edit @Model.BookTitle</h3>
    </div>

    @using (Html.BeginForm("Edit", "Admin",
            FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.BookID)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "BookID":
                    case "PhotoData":
                    case "PhotoMimeType":
                        // do nothing
                        break;
                    default:

                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>
                            @if (property.PropertyName == "Description")
                            {
                                @Html.TextArea(property.PropertyName, null,
                                        new { @class = "form-control", rows = 5 })
                            }
                            else
                            {
                                @Html.TextBox(property.PropertyName, null,
                                        new { @class = "form-control" })
                            }
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                        break;
                }
            }

            <div class="form-group">
                <div style="position:relative;">
                    <label>Image</label>
                    <a class='btn' href='javascript:;'>
                        Choose File...
                        <input type="file" name="Image" size="40"
                               style="position:absolute;z-index:2;top:0;
                            left:0;filter: alpha(opacity=0); opacity:0;
                            background-color:transparent;color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (Model.PhotoData == null)
                {
                    <div class="form-control-static">No Image</div>
                }
                else
                {
                    <img class="img-thumbnail" width="150" height="150"
                         src="@Url.Action("GetImage", "Book",
                        new { Model.BookID })" />
                }
            </div>

        </div>

        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to List", "Index", null, new
            {
                @class = "btn btn-default"
            })
        </div>
    }
</div>

Source/OLLLibrarySystem/Views/Admin/Index.cshtml
@model IEnumerable<OLLLibrarySystem.Domain.Entities.Book>

@{
    ViewBag.Title = "Admin: All Books";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">

    <div class="panel-heading">
        <h3>Complete Library Listing - ADMINISTRATION </h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-center">ID</th>
                <th>Title</th>
                <th>Author</th>
                <th>Genre</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">@item.BookID</td>
                    <td>@Html.ActionLink(item.BookTitle, "Edit", new { item.BookID })</td>
                    <td>@item.Author</td>
                    <td>@item.Genre</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("BookID", item.BookID)
                            <input type="submit"
                                   class="btn btn-danger btn-xs"
                                   value="Delete" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Return to Library", "List", "Book", null,
            new { @class = "btn btn-primary" })

        @Html.ActionLink("Add a new product", "Create", null,
            new { @class = "btn btn-success" })
    </div>

</div>

@*<div class="panel panel-default">


</div>
<h2>All Books</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LexileUpper)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LexileLower)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LocationID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CheckedOutInID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RecAge)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReplacementCost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ISBN)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LexileUpper)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LexileLower)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LocationID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CheckedOutInID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RecAge)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Author)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Photo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReplacementCost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ISBN)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BookID }) |
            @Html.ActionLink("Details", "Details", new { id=item.BookID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.BookID })
        </td>
    </tr>
}

</table>*@